In [1]:
import numpy as np

In [2]:
myarr=np.array([6,8,34,1])

In [3]:
myarr

array([ 6,  8, 34,  1])

In [4]:
myarr[1]


8

In [5]:
myarr.shape

(4,)

In [6]:
myarr.dtype

dtype('int32')

**array creation: Convertion from other python structures**

In [8]:
listarray=np.array([[1,3,4],[2,4,7],[8,3,5]])

In [9]:
listarray

array([[1, 3, 4],
       [2, 4, 7],
       [8, 3, 5]])

In [10]:
listarray.shape


(3, 3)

In [11]:
listarray.size

9

In [12]:
np.array({82,73,7})

array({73, 82, 7}, dtype=object)

In [13]:
zeros=np.zeros((2,5))

In [15]:
zeros.shape

(2, 5)

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
rng=np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace=np.linspace(1,5,5)

In [24]:
lspace

array([1., 2., 3., 4., 5.])

In [25]:
emp=np.empty((4,6))

In [26]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.86921686e-306,
        1.89146896e-307, 7.56571288e-307, 3.11525958e-307],
       [1.24610723e-306, 1.37962320e-306, 1.29060871e-306,
        2.22518251e-306, 1.33511969e-306, 1.78022342e-306],
       [1.05700345e-307, 3.11525958e-307, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306, 1.69119330e-306],
       [1.29062229e-306, 1.24610383e-306, 7.56587584e-307,
        2.22520559e-306, 8.34445137e-308, 1.02353398e-306]])

In [27]:
emp_like=np.empty_like(lspace)

In [28]:
emp_like

array([1., 2., 3., 4., 5.])

In [30]:
ide=np.identity(10)

In [31]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
ide.shape

(10, 10)

In [34]:
ide.size

100

In [35]:
arr=np.arange(99)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr=arr.reshape(3,33)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [46]:
arr=arr.ravel()

In [47]:
arr.shape

(99,)

**Zero access and 1 access**

In [48]:
x=[[1,2,3],[4,5,6],[2,8,9]]

In [49]:
ar=np.array(x)

In [50]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [2, 8, 9]])

In [52]:
ar.sum(axis=0)

array([ 7, 15, 18])

In [53]:
ar.sum(axis=1)

array([ 6, 15, 19])

**Transpose**

In [55]:
ar.T

array([[1, 4, 2],
       [2, 5, 8],
       [3, 6, 9]])

In [56]:
ar.flat

In [60]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
2
8
9


*ndim=number of dimension*

In [61]:
ar.ndim

2

In [62]:
ar.nbytes

36

In [64]:
one =np.array([1,3,4,88,3])

In [65]:
one.argmin()

0

In [66]:
one.argmax()

3

In [67]:
one.argsort()

array([0, 1, 4, 2, 3], dtype=int64)

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [2, 8, 9]])

In [69]:
ar.argmin()

0

In [70]:
ar.argmax()

8

In [71]:
ar.argmax(axis=0)

array([1, 2, 2], dtype=int64)

In [72]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [74]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [75]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 2, 8, 9])

In [82]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [2],
       [8],
       [9]])

In [83]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [2, 8, 9]])

In [85]:
ar2=np.array([[1,3,4],
             [7,9,6]
             ,[6,2,6]])

In [86]:
ar+ar2

array([[ 2,  5,  7],
       [11, 14, 12],
       [ 8, 10, 15]])

In [87]:
ar*ar2

array([[ 1,  6, 12],
       [28, 45, 36],
       [12, 16, 54]])

In [88]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [1.41421356, 2.82842712, 3.        ]])

In [89]:
ar.sum()

40

In [90]:
ar.min()

1

In [91]:
ar.max()

9

In [92]:
np.where(ar>4)

(array([1, 1, 2, 2], dtype=int64), array([1, 2, 1, 2], dtype=int64))

In [93]:
np.count_nonzero(ar)

9

In [94]:
import sys

In [97]:
py_ar=[0,4,55,2]